### ISSUE TITLE
update mypy version requirements

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-cli#147]
Looks like this is related to https://github.com/python/mypy/issues/4563

As a temporary fix, we'll start blacklisting new mypy versions until this is fixed again, but leaving this issue open to remind us to keep checking.

## 0.560

```
186590df9307:aws-encryption-sdk-cli bullocm$ tox -re mypy-py3 -- --show-traceback
GLOB sdist-make: /Users/bullocm/git/aws-encryption-sdk-cli/setup.py
mypy-py3 recreate: /Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3
mypy-py3 installdeps: coverage, mypy!=0.570,!=0.580, mypy_extensions, typing>=3.6.2
mypy-py3 inst: /Users/bullocm/git/aws-encryption-sdk-cli/.tox/dist/aws-encryption-sdk-cli-1.1.4.zip
mypy-py3 installed: asn1crypto==0.24.0,attrs==17.4.0,aws-encryption-sdk==1.3.3,aws-encryption-sdk-cli==1.1.4,boto3==1.7.4,botocore==1.10.4,cffi==1.11.5,coverage==4.5.1,cryptography==2.2.2,docutils==0.14,idna==2.6,jmespath==0.9.3,mypy==0.560,mypy-extensions==0.3.0,psutil==5.4.3,pycparser==2.18,python-dateutil==2.6.1,s3transfer==0.1.13,six==1.11.0,typed-ast==1.1.0,typing==3.6.4,wrapt==1.10.11
mypy-py3 runtests: PYTHONHASHSEED='945863619'
mypy-py3 runtests: commands[0] | python -m mypy --linecoverage-report build src/aws_encryption_sdk_cli/ --show-traceback
mypy-py3 runtests: commands[1] | python -c t = open('.coverage', 'w'); c = open('build/coverage.json').read(); t.write('!coverage.py: This is a private format, don\'t read it directly!\n'); t.write(c);t.close()
mypy-py3 runtests: commands[2] | coverage report -m
Name                                                        Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------
src/aws_encryption_sdk_cli/__init__.py                        116      0   100%
src/aws_encryption_sdk_cli/exceptions.py                        4      0   100%
src/aws_encryption_sdk_cli/internal/__init__.py                 1      0   100%
src/aws_encryption_sdk_cli/internal/arg_parsing.py            183      8    96%   47-54, 75-87
src/aws_encryption_sdk_cli/internal/encoding.py               117      2    98%   263-268
src/aws_encryption_sdk_cli/internal/identifiers.py             20      0   100%
src/aws_encryption_sdk_cli/internal/io_handling.py            156      0   100%
src/aws_encryption_sdk_cli/internal/logging_utils.py           81      0   100%
src/aws_encryption_sdk_cli/internal/master_key_parsing.py      72      0   100%
src/aws_encryption_sdk_cli/internal/metadata.py                89      0   100%
src/aws_encryption_sdk_cli/internal/mypy_types.py              18      0   100%
src/aws_encryption_sdk_cli/key_providers.py                    29      0   100%
-----------------------------------------------------------------------------------------
TOTAL                                                         886     10    99%
__________________________________________________________________________________________________ summary ___________________________________________________________________________________________________
  mypy-py3: commands succeeded
  congratulations :)

```

## 0.570

```
186590df9307:aws-encryption-sdk-cli bullocm$ tox -re mypy-py3 -- --show-traceback
GLOB sdist-make: /Users/bullocm/git/aws-encryption-sdk-cli/setup.py
mypy-py3 recreate: /Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3
mypy-py3 installdeps: coverage, mypy, mypy_extensions, typing>=3.6.2
mypy-py3 inst: /Users/bullocm/git/aws-encryption-sdk-cli/.tox/dist/aws-encryption-sdk-cli-1.1.4.zip
mypy-py3 installed: asn1crypto==0.24.0,attrs==17.4.0,aws-encryption-sdk==1.3.3,aws-encryption-sdk-cli==1.1.4,boto3==1.7.4,botocore==1.10.4,cffi==1.11.5,coverage==4.5.1,cryptography==2.2.2,docutils==0.14,idna==2.6,jmespath==0.9.3,mypy==0.580,mypy-extensions==0.3.0,pycparser==2.18,python-dateutil==2.6.1,s3transfer==0.1.13,six==1.11.0,typed-ast==1.1.0,typing==3.6.4,wrapt==1.10.11
mypy-py3 runtests: PYTHONHASHSEED='996840928'
mypy-py3 runtests: commands[0] | python -m mypy --linecoverage-report build src/aws_encryption_sdk_cli/ --show-traceback
src/aws_encryption_sdk_cli/internal/metadata.py:47: error: "ib" does not return a value
src/aws_encryption_sdk_cli/internal/metadata.py:48: error: Argument 1 to "instance_of" has incompatible type "Tuple[Type[str]]"; expected "Union[Tuple[Type[None], ...], Type[None]]"
src/aws_encryption_sdk_cli/internal/metadata.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.580
Traceback (most recent call last):
  File "/Users/bullocm/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/bullocm/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/__main__.py", line 11, in <module>
    main(None)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/main.py", line 88, in main
    type_check_only(sources, bin_dir, options, flush_errors)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/main.py", line 137, in type_check_only
    flush_errors=flush_errors)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 179, in build
    flush_errors, fscache)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 264, in _build
    graph = dispatch(sources, manager)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 2056, in dispatch
    process_graph(graph, manager)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 2341, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 2482, in process_stale_scc
    graph[id].finish_passes()
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 1935, in finish_passes
    manager.report_file(self.tree, self.type_map(), self.options)
  File "/Users/bullocm/.pyenv/versions/3.6.2/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 1690, in wrap_context
    yield
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 1935, in finish_passes
    manager.report_file(self.tree, self.type_map(), self.options)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/build.py", line 747, in report_file
    self.reports.file(file, type_map, options)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/report.py", line 74, in file
    reporter.on_file(tree, type_map, options)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/report.py", line 348, in on_file
    tree.accept(coverage_visitor)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/nodes.py", line 237, in accept
    return visitor.visit_mypy_file(self)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/traverser.py", line 30, in visit_mypy_file
    d.accept(self)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/nodes.py", line 745, in accept
    return visitor.visit_class_def(self)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/traverser.py", line 62, in visit_class_def
    o.defs.accept(self)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/nodes.py", line 807, in accept
    return visitor.visit_block(self)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/traverser.py", line 34, in visit_block
    s.accept(self)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/nodes.py", line 542, in accept
    return visitor.visit_func_def(self)
  File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/lib/python3.6/site-packages/mypy/report.py", line 318, in visit_func_def
    assert start_indent is not None and start_indent > old_indent
AssertionError: 
src/aws_encryption_sdk_cli/internal/metadata.py: : note: use --pdb to drop into pdb
ERROR: InvocationError: '/Users/bullocm/git/aws-encryption-sdk-cli/.tox/mypy-py3/bin/python -m mypy --linecoverage-report build src/aws_encryption_sdk_cli/ --show-traceback'
__________________________________________________________________________________________________ summary ___________________________________________________________________________________________________
ERROR:   mypy-py3: commands failed

```

**Comment by mattsb42-aws** [comment]
This should not have been closed...not sure why I did.

In testing with the test vector handlers package today, it looks like this was fixed in mypy in ~May-ish. My current thinking is to go with `>=0.600` for now.
