### ISSUE TITLE
AttributeError: module 'attr' has no attribute 's'

### ISSUE THREAD

**Issue by mrichman** [aws/aws-encryption-sdk-cli#160]
I just installed for the first time using `pip install --user aws-encryption-sdk-cli` (Python 3.7 on macOS) and I get this error on first use:

```
$ aws-encryption-cli
Traceback (most recent call last):
  File "/User/Mark/Library/Python/3.7/bin/aws-encryption-cli", line 6, in <module>
    from aws_encryption_sdk_cli import cli
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk_cli/__init__.py", line 21, in <module>
    import aws_encryption_sdk
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk/__init__.py", line 15, in <module>
    from aws_encryption_sdk.caches.local import LocalCryptoMaterialsCache  # noqa
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk/caches/__init__.py", line 25, in <module>
    from ..internal.formatting.encryption_context import serialize_encryption_context
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk/internal/formatting/__init__.py", line 14, in <module>
    from .serialize import serialize_header
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk/internal/formatting/serialize.py", line 21, in <module>
    from aws_encryption_sdk.internal.crypto.encryption import encrypt
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk/internal/crypto/__init__.py", line 15, in <module>
    from .wrapping_keys import WrappingKey  # noqa
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk/internal/crypto/wrapping_keys.py", line 23, in <module>
    from ..structures import EncryptedData
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/aws_encryption_sdk/internal/structures.py", line 18, in <module>
    @attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'
```

**Comment by karlw00t** [comment]
Do you have an attr.py file in your local directory? Python will pick that up, and ignore the attrs package in your site packages.

**Comment by karlw00t** [comment]
I'm going to close this. Please reopen this issue if you are still running into issues.
