### ISSUE TITLE
NotSupportedError("Unsupported type 2 discovered in data stream", "2 is not a valid ObjectType")

### ISSUE THREAD

**Issue by rohanmohapatra** [aws/aws-encryption-sdk-cli#174]
Command tried:
```
aws-encryption-cli --decrypt --input file.encrypted --encryption-context key1=value1 -S --decode --output . 
```

StackTrace
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 101, in _verified_message_type_from_id
    return ObjectType(message_type_id)
  File "/usr/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid ObjectType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk_cli/__init__.py", line 256, in cli
    process_cli_request(stream_args, args)
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk_cli/__init__.py", line 204, in process_cli_request
    handler.process_single_file(stream_args=stream_args, source=_source, destination=_destination)
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 338, in process_single_file
    operation_result = self.process_single_operation(
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 270, in process_single_operation
    return self._single_io_write(
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 212, in _single_io_write
    header=json_ready_header(handler.header),
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 194, in header
    self._prep_message()
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 733, in _prep_message
    self._header, self.header_auth = self._read_header()
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 746, in _read_header
    header, raw_header = deserialize_header(self.source_stream)
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 247, in deserialize_header
    header["type"] = _verified_message_type_from_id(message_type_id)
  File "/home/rohan/.local/lib/python3.8/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 103, in _verified_message_type_from_id
    raise NotSupportedError("Unsupported type {} discovered in data stream".format(message_type_id), error)
aws_encryption_sdk.exceptions.NotSupportedError: ('Unsupported type 2 discovered in data stream', ValueError('2 is not a valid ObjectType'))

Encountered unexpected error: increase verbosity to see details.
NotSupportedError("Unsupported type 2 discovered in data stream", "2 is not a valid ObjectType")
```

**Comment by MatthewBennington** [comment]
That error indicates that the second byte of your encrypted message is invalid.

The first two bytes of the AWS Encryption SDK's message format are constant (`0x01`, `0x80`). Looks like the second byte of your input was `0x02`, which is not a valid value. You can read more about the details of the message format in the specification [here](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/data-format/message-header.md#header-body).

It seems like what your trying to decrypt either isn't an AWS ESDK message, or was corrupted somehow.

**Comment by acioc** [comment]
Resolving per answer above. Please re-open this issue (or create a new one) if there are additional questions or you would like us to dive a bit deeper into anything.
