### ISSUE TITLE
Unable to decrypt any data key

### ISSUE THREAD

**Issue by woltsu** [aws/aws-encryption-sdk-cli#195]
Hello. I'm able to encrypt a file using:
```bash
cat file.txt | aws-encryption-sdk-cli --encrypt -i - --wrapping-keys key=<key> region=<region> --encode -S --output - > file.encrypted
```

But decryption using:
```bash
cat file.encrypted | aws-encryption-sdk-cli --decrypt -i - --wrapping-keys key=<key> region=<region> --decode -S --output - -vvvv > file.decrypted
```

Gives the following output:
```
2020-12-29 12:39:57,462 - MainThread - aws_encryption_sdk_cli - DEBUG - Encryption mode: decrypt
2020-12-29 12:39:57,462 - MainThread - aws_encryption_sdk_cli - DEBUG - Encryption source: -
2020-12-29 12:39:57,463 - MainThread - aws_encryption_sdk_cli - DEBUG - Encryption destination: -
2020-12-29 12:39:57,463 - MainThread - aws_encryption_sdk_cli - DEBUG - Wrapping key provider configuration: [{'key': ['<key>'], 'region': ['<region>'], 'provider': 'aws-encryption-sdk-cli::aws-kms', 'discovery': False}]
2020-12-29 12:39:57,463 - MainThread - aws_encryption_sdk_cli - DEBUG - Suffix requested: None
2020-12-29 12:39:57,463 - MainThread - aws_encryption_sdk_cli - DEBUG - Loading provider: aws-encryption-sdk-cli::aws-kms
2020-12-29 12:39:57,464 - MainThread - aws_encryption_sdk_cli - DEBUG - Discovering master key provider plugins
2020-12-29 12:39:57,466 - MainThread - aws_encryption_sdk_cli - INFO - Collecting plugin "aws-kms" registered by "aws-encryption-sdk-cli 2.1.0"
2020-12-29 12:39:57,467 - MainThread - aws_encryption_sdk_cli - DEBUG - Plugin details: {'name': 'aws-kms', 'module_name': 'aws_encryption_sdk_cli.key_providers', 'attrs': ('aws_kms_master_key_provider',), 'extras': (), 'dist': aws-encryption-sdk-cli 2.1.0 (/usr/lib/python3.8/site-packages)}
2020-12-29 12:39:57,548 - MainThread - botocore.hooks - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2020-12-29 12:39:57,550 - MainThread - botocore.hooks - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2020-12-29 12:39:57,551 - MainThread - botocore.hooks - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2020-12-29 12:39:57,554 - MainThread - botocore.hooks - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2020-12-29 12:39:57,554 - MainThread - botocore.hooks - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2020-12-29 12:39:57,555 - MainThread - botocore.hooks - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2020-12-29 12:39:57,556 - MainThread - botocore.hooks - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2020-12-29 12:39:57,560 - MainThread - botocore.hooks - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2020-12-29 12:39:57,560 - MainThread - botocore.hooks - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2020-12-29 12:39:57,560 - MainThread - botocore.hooks - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2020-12-29 12:39:57,560 - MainThread - botocore.hooks - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2020-12-29 12:39:57,564 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2020-12-29 12:39:57,566 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-12-29 12:39:57,567 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2020-12-29 12:39:57,567 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.8/site-packages/botocore/data/endpoints.json
2020-12-29 12:39:57,587 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fbf0d3b9310>
2020-12-29 12:39:57,600 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.8/site-packages/botocore/data/kms/2014-11-01/service-2.json
2020-12-29 12:39:57,605 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.kms: calling handler <function add_generate_presigned_url at 0x7fbf0d3e8a60>
2020-12-29 12:39:57,606 - MainThread - botocore.endpoint - DEBUG - Setting kms timeout as (60, 60)
2020-12-29 12:39:57,607 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.8/site-packages/botocore/data/_retry.json
2020-12-29 12:39:57,608 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: kms
2020-12-29 12:39:57,609 - MainThread - aws_encryption_sdk.internal.formatting.deserialize - DEBUG - Starting header deserialization
2020-12-29 12:39:57,609 - MainThread - aws_encryption_sdk.internal.formatting.deserialize - DEBUG - Deserializing header in version V2
2020-12-29 12:39:57,610 - MainThread - aws_encryption_sdk.internal.formatting.encryption_context - DEBUG - Found 1 keys
2020-12-29 12:39:57,610 - MainThread - aws_encryption_sdk.key_providers.base - DEBUG - starting decrypt data key attempt
2020-12-29 12:39:57,610 - MainThread - aws_encryption_sdk.key_providers.base - DEBUG - attempting to locate master key from key provider: aws-kms
2020-12-29 12:39:57,610 - MainThread - aws_encryption_sdk.key_providers.base - DEBUG - attempting to locate master key from key provider: aws-kms
2020-12-29 12:39:57,611 - MainThread - aws_encryption_sdk.key_providers.base - DEBUG - using existing master key
2020-12-29 12:39:57,611 - MainThread - aws_encryption_sdk.key_providers.base - DEBUG - attempting to decrypt data key with provider b'<arn>'
2020-12-29 12:39:57,611 - MainThread - aws_encryption_sdk.key_providers.base - INFO - decrypting data key with encryption context: {'aws-crypto-public-key': '<public-key>'}
2020-12-29 12:39:57,611 - MainThread - aws_encryption_sdk.key_providers.base - DEBUG - IncorrectMasterKeyError("Provided data key provider MasterKeyInfo(provider_id='aws-kms', key_info=b'<arn>') does not match Master Key provider MasterKeyInfo(provider_id='aws-kms', key_info=b'<key>')") raised when attempting to decrypt data key with master key MasterKeyInfo(provider_id='aws-kms', key_info=b'<key>')
2020-12-29 12:39:57,612 - MainThread - aws_encryption_sdk.streaming_client - DEBUG - Closing stream
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 216, in _single_io_write
    header=json_ready_header(handler.header),
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 204, in header
    self._prep_message()
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 774, in _prep_message
    self._header, self.header_auth = self._read_header()
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 810, in _read_header
    decryption_materials = self.config.materials_manager.decrypt_materials(request=decrypt_materials_request)
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/materials_managers/default.py", line 150, in decrypt_materials
    data_key = self.master_key_provider.decrypt_data_key_from_list(
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/key_providers/base.py", line 288, in decrypt_data_key_from_list
    raise DecryptKeyError("Unable to decrypt any data key")
aws_encryption_sdk.exceptions.DecryptKeyError: Unable to decrypt any data key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 214, in __exit__
    self.close()
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 975, in close
    raise SerializationError("Footer not read")
aws_encryption_sdk.exceptions.SerializationError: Footer not read

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/logging_utils.py", line 137, in format
    _record = self.__redact_record(record)
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/logging_utils.py", line 123, in __redact_record
    _record = copy.deepcopy(record)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'traceback' object
Call stack:
  File "/usr/bin/aws-encryption-cli", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/__init__.py", line 283, in cli
    process_cli_request(stream_args, args)
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/__init__.py", line 192, in process_cli_request
    handler.process_single_operation(
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 274, in process_single_operation
    return self._single_io_write(
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 248, in _single_io_write
    _destination.flush()
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 218, in __exit__
    _LOGGER.exception("Error on closing")
Message: 'Error on closing'
Arguments: ()
2020-12-29 12:39:57,614 - MainThread - aws_encryption_sdk_cli - DEBUG - Encountered unexpected error: increase verbosity to see details.
DecryptKeyError("Unable to decrypt any data key")
2020-12-29 12:39:57,614 - MainThread - aws_encryption_sdk_cli - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/__init__.py", line 283, in cli
    process_cli_request(stream_args, args)
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/__init__.py", line 192, in process_cli_request
    handler.process_single_operation(
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 274, in process_single_operation
    return self._single_io_write(
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 216, in _single_io_write
    header=json_ready_header(handler.header),
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 204, in header
    self._prep_message()
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 774, in _prep_message
    self._header, self.header_auth = self._read_header()
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 810, in _read_header
    decryption_materials = self.config.materials_manager.decrypt_materials(request=decrypt_materials_request)
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/materials_managers/default.py", line 150, in decrypt_materials
    data_key = self.master_key_provider.decrypt_data_key_from_list(
  File "/usr/lib/python3.8/site-packages/aws_encryption_sdk/key_providers/base.py", line 288, in decrypt_data_key_from_list
    raise DecryptKeyError("Unable to decrypt any data key")
aws_encryption_sdk.exceptions.DecryptKeyError: Unable to decrypt any data key

2020-12-29 12:39:57,615 - MainThread - aws_encryption_sdk.streaming_client - DEBUG - Closing stream
Encountered unexpected error: increase verbosity to see details.
DecryptKeyError("Unable to decrypt any data key")
```

The user who is attached to the KMS key has the following policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kms:EnableKeyRotation",
                "kms:EnableKey",
                "kms:ImportKeyMaterial",
                "kms:GetPublicKey",
                "kms:Decrypt",
                "kms:UpdateKeyDescription",
                "kms:GetKeyPolicy",
                "kms:GenerateDataKeyWithoutPlaintext",
                "kms:Verify",
                "kms:CancelKeyDeletion",
                "kms:DeleteImportedKeyMaterial",
                "kms:GenerateDataKeyPairWithoutPlaintext",
                "kms:DisableKey",
                "kms:GenerateDataKeyPair",
                "kms:ReEncryptFrom",
                "kms:DisableKeyRotation",
                "kms:GetParametersForImport",
                "kms:Encrypt",
                "kms:GetKeyRotationStatus",
                "kms:ScheduleKeyDeletion",
                "kms:GenerateDataKey",
                "kms:ReEncryptTo",
                "kms:DescribeKey",
                "kms:Sign"
            ],
            "Resource": "<arn>"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "kms:DescribeCustomKeyStores",
                "kms:ListKeys",
                "kms:DeleteCustomKeyStore",
                "kms:GenerateRandom",
                "kms:UpdateCustomKeyStore",
                "kms:ListAliases",
                "kms:DisconnectCustomKeyStore",
                "kms:CreateKey",
                "kms:ConnectCustomKeyStore",
                "kms:CreateCustomKeyStore"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by woltsu** [comment]
Of course I got it to work right after creating this issue... The problem was I gave the KMS key id as the key parameter, but when I changed that to the arn of the key it began to work. Not sure if this is intended behaviour or not, but works now!

**Comment by woltsu** [comment]
For anyone who stumbles upon this issue in the future, I created a docker image for this tool and scripts for encrypting & decrypting: https://github.com/woltsu/aws-encryption-sdk-cli-docker.

**Comment by alex-chew** [comment]
Hi woltsu,

Thanks for reaching out, and I'm glad you were able to resolve your issue. Just to clarify, I think the "KMS key id" you mentioned was probably a [KMS key alias](https://docs.aws.amazon.com/kms/latest/developerguide/kms-alias.html). The behavior you're seeing is expected - version 2.1.x of the Encryption SDK CLI doesn't support decrypting using KMS aliases, you'll need to use a KMS key ARN instead. While the docs do mention this, we'll look into improving the docs to make this behavior clearer.

I'm going to close this issue but please feel free to re-open it if you have any further questions or concerns.

**Comment by atanasoff-yordan** [comment]
I was having the same issue, the solution for me was to add the lambda execution role to kms key execution policies.

**Comment by yi-varicent** [comment]
> I was having the same issue, the solution for me was to add the lambda execution role to kms key execution policies.

same, except it was kms:decrypt role statement on my ecs instance
